sudo: required
services:
    - docker
language: c
env:
  global:
  - ROCKER_VERSION=1.3.0
  - secure: "YKBHru1Io3CTly6l8YAmR8Qcrs4bhx3L1xVNHgAGglt0ckY0OJHM/nEndgML/ZWNf3Yu0XPdxTEtEbsLONG3IqWjx1hNNIVb30W3IQBH5KTXFerEtjPOPG0qh3ApnInGflY5WAFioPHqk3wXaB/xm1yyDSdUhb/diomDAvbBF0g="
  - secure: "Vzv9SX9uFkWcEibqgfg2PuGi9V6fCgMbnV5AS1AxXfFQSz9pnPS30LLaAFpNvzDpAZyLowG+G0RTz78bgaNweSLVYoIW/udQbaLSqrWIL48bYBF7A4GSUdknWNBVprnbNb7PT/BENvW/Z00RMrubQa8h0ksDamJ/teTGC1vAsBE="
before_script:
  - curl -L https://github.com/grammarly/rocker/releases/download/${ROCKER_VERSION}/rocker_linux_amd64.tar.gz | sudo tar -C /usr/bin -xzf -
script:
  - rocker build --no-cache;
after_success:
  - if [[ "${TRAVIS_BRANCH}" = "sphinx" ]]; then rocker build --push --auth $DOCKER_USER:$DOCKER_PASS ; fi
