sudo: false
language: python
cache: pip

install:
    - pip install -r requirements.txt

script:
    - make html

after_success:
    - if [[ $TRAVIS_PULL_REQUEST != 'false' ]]; then
      rsync -av --del build/html/ travis@202.141.176.110::help/preview/;
      fi

deploy:
    provider: script
    script: rsync -av --del --filter=P_preview/ build/html/ travis@202.141.176.110::help/
    on:
        branch: master
        condition: '-n "$RSYNC_PASSWORD"'
    skip_cleanup: true
