sudo: false
language: python
cache: pip

install:
    - pip install -r requirements.txt

script:
    - make html

deploy:
    provider: script
    script: rsync -av build/html/ travis@202.141.176.110::help/
    on:
        branch: sphinx
        condition: '-n "$RSYNC_PASSWORD"'
    skip_cleanup: true
